# Generated by Django 5.2.4 on 2025-09-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banner_popup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Popup',
        ),
    ]
