# Generated by Django 5.2.4 on 2025-10-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_banner_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title displayed below the image', max_length=150)),
                ('image', models.ImageField(upload_to='home_categories/')),
                ('link', models.URLField(blank=True, help_text='Optional URL for this tile', max_length=500, null=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order in which it appears on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Category',
                'verbose_name_plural': 'Home Categories',
                'ordering': ['position'],
            },
        ),
    ]
