# Generated by Django 5.2.4 on 2025-10-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_homecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecategory',
            options={'verbose_name': 'Home Category', 'verbose_name_plural': 'Home Categories'},
        ),
    ]
