# Generated by Django 5.2.4 on 2025-10-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_homecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecategory',
            options={},
        ),
    ]
