# Generated by Django 5.2.4 on 2025-10-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_vendorpayout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorpayout',
            options={},
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the payout.', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='admin_remarks',
            field=models.CharField(blank=True, help_text='Remarks or notes from the admin regarding this payout.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total payout amount to the vendor.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='method',
            field=models.CharField(blank=True, help_text='Payment method used (e.g. Bank, eSewa, Khalti, PayPal, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction or reference ID from the payment gateway.', max_length=100),
        ),
    ]
