# Generated by Django 5.2.4 on 2025-10-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_vendorpayout_options_vendorpayout_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorpayout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='method',
            field=models.CharField(blank=True, help_text='Payment method used (e.g. Bank, eSewa, Khalti, etc.)', max_length=100),
        ),
        migrations.CreateModel(
            name='VendorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Commission rate as a decimal e.g. 0.1000 for 10%', max_digits=5)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='dashboard.vendor')),
            ],
            options={
                'ordering': ['-active', '-effective_from', '-created_at'],
            },
        ),
    ]
