# Generated by Django 5.2.4 on 2025-10-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_vendorpayout_options_alter_vendorpayout_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField(blank=True, help_text='Optional message from vendor to admin')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Admin notes or reason for approval/rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='dashboard.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
