# Generated by Django 5.2.4 on 2025-10-15 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_vendorpayoutrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ManyToManyField(related_name='role', to=settings.AUTH_USER_MODEL),
        ),
    ]
