# Generated by Django 5.2.4 on 2025-10-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_userrole_is_admin_remove_userrole_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compare_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
