# Generated by Django 5.2.4 on 2025-10-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('weight', 'Weight'), ('storage', 'Storage Capacity'), ('ram', 'RAM'), ('material', 'Material'), ('style', 'Style'), ('pattern', 'Pattern'), ('flavor', 'Flavor'), ('other', 'Other')], max_length=20),
        ),
    ]
