# Generated by Django 5.2.4 on 2025-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_productvariant_variant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='position',
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('products', 'Products Page'), ('about', 'About Page')], default='home', help_text='Select where to display the banner', max_length=50, unique=True),
        ),
    ]
