# Generated by Django 5.2.4 on 2025-10-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_category_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('products', 'Products Page')], default='home', help_text='Select where to display the banner', max_length=50, unique=True),
        ),
    ]
