# Generated by Django 5.2.4 on 2025-10-27 10:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_userprofile_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorcommission',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendorcommission',
            name='active',
        ),
        migrations.RemoveField(
            model_name='vendorcommission',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='vendorcommission',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='vendorcommission',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Commission rate as a decimal (e.g. 0.10 for 10%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='dashboard.vendor')),
            ],
        ),
    ]
