# Generated by Django 5.2.4 on 2025-10-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_vendorcommission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorpayoutrequest',
            name='message',
        ),
    ]
