# Generated by Django 5.2.4 on 2025-10-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_vendorpayoutrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
