# Generated by Django 5.2.4 on 2025-10-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_vendorpayoutrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the payout.', max_length=20),
        ),
    ]
