# Generated by Django 5.2.4 on 2025-10-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_vendorpayout_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingZone',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fulfillment_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_account_holder',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_qr/'),
        ),
        migrations.DeleteModel(
            name='VendorPayout',
        ),
    ]
