# Generated by Django 5.2.4 on 2025-10-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
