# Generated by Django 5.2.4 on 2025-10-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeCategory',
        ),
    ]
