# Generated by Django 5.2.4 on 2025-10-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_delete_homecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
    ]
