# Generated by Django 5.2.4 on 2025-10-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_remove_vendor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tagline',
        ),
    ]
