# Generated by Django 5.2.4 on 2025-11-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_otpverification_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g. 13 for 13%)', max_digits=5)),
                ('estimated_days', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
    ]
