# Generated by Django 5.2.4 on 2025-11-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_shippingzone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingZone',
            new_name='ShippingCost',
        ),
    ]
