# Generated by Django 5.2.4 on 2025-11-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_rename_shippingzone_shippingcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcost',
            name='estimated_days',
        ),
    ]
