# Generated by Django 5.2.4 on 2025-11-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_remove_shippingcost_estimated_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Calculated expected delivery date', null=True),
        ),
    ]
