# Generated by Django 5.2.4 on 2025-11-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
    ]
