# Generated by Django 5.2.4 on 2025-11-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_remove_order_admin_notes_remove_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('imepay', 'IME Pay'), ('connectips', 'ConnectIPS')], default='cod', max_length=20),
        ),
    ]
