# Generated by Django 5.2.4 on 2025-11-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_otpverification_tmp_email_alter_otpverification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='tmp_email',
        ),
    ]
