# Generated by Django 5.2.4 on 2025-11-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_remove_otpverification_tmp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='expires_at',
        ),
    ]
