# Generated by Django 5.2.4 on 2025-11-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_alter_userprofile_gender_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
    ]
