# Generated by Django 5.2.4 on 2025-11-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
