# Generated by Django 5.2.4 on 2025-11-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_rename_date_created_invoice_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
    ]
