# Generated by Django 5.2.4 on 2025-11-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_remove_orderitem_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tax',
            new_name='tax_amount',
        ),
    ]
