# Generated by Django 5.2.4 on 2025-11-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_rename_tax_invoice_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
    ]
