# Generated by Django 5.2.4 on 2025-11-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_alter_vendor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
