# Generated by Django 5.2.4 on 2025-11-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_alter_order_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorwallet',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorpayoutrequest',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='vendors',
        ),
        migrations.DeleteModel(
            name='VendorCommission',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For  tracking', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
        migrations.DeleteModel(
            name='VendorWallet',
        ),
        migrations.DeleteModel(
            name='VendorPayoutRequest',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
