# Generated by Django 5.2.4 on 2025-11-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, choices=[('Koshi Province', 'Koshi Province'), ('Madhesh Province', 'Madhesh Province'), ('Bagmati Province', 'Bagmati Province'), ('Gandaki Province', 'Gandaki Province'), ('Lumbini Province', 'Lumbini Province'), ('Karnali Province', 'Karnali Province'), ('Sudurpashchim Province', 'Sudurpashchim Province')], max_length=50, null=True),
        ),
    ]
