# Generated by Django 5.2.4 on 2025-11-23 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_purchaseinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='invoice_number',
            new_name='supplier_invoice_number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_order_number',
            field=models.CharField(blank=True, help_text='Purchase order number', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name at time of purchase', max_length=255)),
                ('product_sku', models.CharField(blank=True, help_text='Product SKU at time of purchase', max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of purchase', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.purchaseinvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name at time of purchase', max_length=255)),
                ('product_sku', models.CharField(blank=True, help_text='Product SKU at time of purchase', max_length=100, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price per unit paid to supplier', max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='dashboard.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.purchase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
