# Generated by Django 5.2.4 on 2025-11-17 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_alter_order_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='citizenship_front',
            field=models.FileField(blank=True, help_text='Front side of citizenship', upload_to='kyc/citizenship/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_registration',
            field=models.FileField(blank=True, help_text='For companies: Company registration certificate', upload_to='kyc/company/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
