# Generated by Django 5.2.4 on 2025-11-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_alter_vendor_citizenship_front_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
    ]
