# Generated by Django 5.2.4 on 2025-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_rename_invoice_number_purchase_supplier_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Product image at time of purchase', null=True, upload_to='purchases/products/'),
        ),
    ]
