# Generated by Django 5.2.4 on 2025-11-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_purchaseitem_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_order_number',
            field=models.CharField(blank=True, help_text='Purchase order number', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Product image at time of purchase', null=True, upload_to='purchase_invoice_items/'),
        ),
    ]
