# Generated by Django 5.2.4 on 2025-11-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_product_shipping_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=13, help_text='Tax percentage (e.g. 13 for 13%)', max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingCost',
        ),
    ]
