# Generated by Django 5.2.4 on 2025-11-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_alter_product_main_image_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g. 13 for 13%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Tax Setting',
                'verbose_name_plural': 'Tax Settings',
            },
        ),
        migrations.DeleteModel(
            name='ShippingCost',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='estimated_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_days',
            field=models.CharField(blank=True, help_text='Estimated delivery time (days or string like "2-4 days")', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost per unit for this product', max_digits=10),
        ),
    ]
