# Generated by Django 5.2.4 on 2025-11-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_taxrate_delete_shippingcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage (e.g., 13 for 13%)', max_digits=5),
        ),
    ]
