# Generated by assistant - add order.estimated_days field
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_taxcost_delete_shippingcost_orderitem_estimated_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_days',
            field=models.CharField(blank=True, max_length=100, null=True, help_text='Estimated delivery summary (e.g. 2-4 days)'),
        ),
    ]
