# Generated by Django 5.2.4 on 2025-11-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_remove_order_tax_order_tax_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='citizenship_number',
        ),
    ]
