# Generated by Django 5.2.4 on 2025-11-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_add_shipping_and_tax'),
        ('dashboard', '0064_add_order_estimated_days'),
    ]

    operations = [
    ]
