# Generated by Django 5.2.4 on 2025-11-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_remove_vendor_citizenship_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='citizenship_number',
            field=models.CharField(blank=True, help_text='For individuals', max_length=20),
        ),
    ]
