# Generated by Django 5.2.4 on 2025-11-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_vendor_citizenship_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ax_percentage',
            field=models.DecimalField(decimal_places=2, default=13, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
