# Generated by Django 5.2.4 on 2025-12-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_merge_20251125_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
