# Generated by Django 5.2.4 on 2025-11-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_invoice_ax_percentage_invoice_shipping_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='ax_percentage',
            new_name='tax_percentage',
        ),
    ]
