# Generated by Django 5.2.4 on 2025-11-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_alter_userprofile_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.ManyToManyField(blank=True, to='dashboard.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ManyToManyField(blank=True, to='dashboard.productvariant'),
        ),
    ]
