# Generated by Django 4.2.14 on 2025-11-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_remove_cart_variant_remove_orderitem_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_date',
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Calculated expected delivery date', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
