# Generated by Django 4.2.14 on 2025-11-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_remove_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Calculated expected delivery date', null=True),
        ),
    ]
