# Generated by Django 4.2.14 on 2025-11-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='estimated_delivery_date',
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days for delivery from order date', null=True),
        ),
    ]
