# Generated by Django 5.2.4 on 2025-11-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_remove_product_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_purchase',
        ),
    ]
