# Generated by Django 5.2.4 on 2025-11-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_remove_coupon_description_remove_coupon_max_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='vendors',
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order value', max_digits=10),
        ),
    ]
